### PR TITLE
Run spellcheck.js on spellcheck.js

### PR DESCRIPTION
**Pull request by dancyfits**
Not really.  Just fixes a few glaring spelling errors.  Of course, comments can be whatever the dev damn well pleases, but the principle... spelling errors in a spellchecker?  Had to intervene.

### CODE REVIEW

**Comment by Johanndutoit** [comment]
love it haha, apologies was traveling for a bit there. That's what happens when you mind share 15 repos :). Tested passed and proper spelling going in now! whoop whoop

**Comment by Johanndutoit** [comment]
Don't think we should do a point release for this just yet, seeing as it doesn't change logic just much needed spellchecking haha

**Comment by dancyfits** [comment]
Haha, and I don't think users will mind too much what the comments say. Although, maybe a point release for each word will make them think that it's improving super fast 😈

**Comment by Johanndutoit** [comment]
Dr. Evil

**Pull request merged**
